version: '3.1'

services:
    demo:
        image: node:current-alpine
        working_dir: /home/node/app
        ports:
            - "3000:3000"
        volumes:
            - ./:/home/node/app
        command: "sh -c 'yarn install && yarn demo'"
