name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn run lint

      - name: Build
        env:
          OF_DEMO_ROOT_PATH: "/oceanfront/"
        run: yarn run build

      - name: Run unit tests
        run: yarn run test

      - if: "github.event_name == 'push' || github.event_name == 'workflow_dispatch'"
        name: Deploy demo site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/demo/dist
