name: Build Packages

on:
  push:
  pull_request:
    branches:
      - main

steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v1
    with:
      node-version: "12.x"
  - run: yarn install
  - run: yarn build
